#!/bin/bash
set -e

echo "Checking if host mounted data directory is empty..."
if [ -d "/srv/tfs/data" ] && [ -z "$(ls -A /srv/tfs/data 2>/dev/null)" ]; then
    echo "Host data directory is empty. Copying base datapack..."
    cp -a /srv/tfs-base-data/* /srv/tfs/data/
    echo "Base datapack initialized."
fi

# The schema.sql is handled slightly differently since it's a single file mount
# If Docker created an empty directory instead of a file due to a missing host file
if [ -d "/srv/tfs/schema.sql" ]; then
    echo "WARNING: /srv/tfs/schema.sql is a directory instead of a file."
    echo "This happens when the host file doesn't exist before 'docker compose up'."
    echo "Attempting to fix by moving directory and replacing with file..."
    rm -rf /srv/tfs/schema.sql
    cp /srv/tfs-base-data/schema.sql /srv/tfs/schema.sql
fi

if [ ! -f "/srv/tfs/schema.sql" ]; then
    echo "schema.sql is completely missing, copying base..."
    cp /srv/tfs-base-data/schema.sql /srv/tfs/schema.sql
fi

echo "Waiting for MySQL database to be ready..."
until mysqladmin ping -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" --silent; do
    echo "MySQL is unavailable - sleeping..."
    sleep 2
done

echo "MySQL is up - checking if database needs initialization..."
TABLES=$(mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -D"$MYSQL_DATABASE" -e "SHOW TABLES LIKE 'players';" | wc -l)

if [ "$TABLES" -eq 0 ]; then
    echo "Initializing database..."
    mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -D"$MYSQL_DATABASE" < /srv/tfs/schema.sql
    echo "Database initialized."
else
    echo "Database already initialized."
fi

echo "Starting server..."
# The binary generated by the fork's cmake build is usually called theforgottenserver
cd /srv/tfs && ./build/theforgottenserver
